version: '3'
services:
    jhipster-logstash:
        build: jhipster-logstash/
        image: klikus/jhipster-logstash:7.6.2-1.00
        environment:
            - INPUT_TCP_PORT=5000
            - INPUT_UDP_PORT=5000
            - ELASTICSEARCH_HOST=http://jhipster-elasticsearch
            - ELASTICSEARCH_PORT=9200
            - LOGSTASH_DEBUG=false
            - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - 5000:5000
          - 5000:5000/udp
        depends_on:
          - jhipster-elasticsearch
    jhipster-kibana:
        build: jhipster-kibana/
        image: klikus/jhipster-kibana:7.6.2-1.01
        environment:
            - ELASTICSEARCH_HOSTS=http://jhipster-elasticsearch:9200
        ports:
            - 5601:5601
        depends_on:
            - jhipster-elasticsearch
    jhipster-elasticsearch:
        build: jhipster-elasticsearch/
        image: klikus/jhipster-elasticsearch:7.6.2-1.01
        ports:
        - 9200:9200
        environment:
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    jhipster-import-dashboards:
        build: jhipster-import-dashboards/
        image: klikus/jhipster-import-dashboards:7.6.2-1.00
        environment:
          - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
          - KIBANA_URL=http://jhipster-kibana:5601
        depends_on:
          - jhipster-elasticsearch
          - jhipster-kibana
    nginx:
        build: nginx/
        image: klikus/nginx:1.02
